/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens;

import Models.NhanVien;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class MainMenu extends javax.swing.JFrame {

        /**
         * Creates new form mAINmENU
         */
        public MainMenu() {
                initComponents();
                setLocationRelativeTo(null);
                setResizable(false);
        }

        NhanVien account;

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                btnQuayOrder = new javax.swing.JButton();
                btnLichSu = new javax.swing.JButton();
                btnDsdv = new javax.swing.JButton();
                btnDatBan = new javax.swing.JButton();
                btnThongKe = new javax.swing.JButton();
                btnDsnv = new javax.swing.JButton();
                btnLogOut = new javax.swing.JButton();
                btnInfo = new javax.swing.JButton();
                txtAccount = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(197, 225, 172));

                jPanel2.setBackground(new java.awt.Color(61, 131, 24));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("QUẢN LÝ NHÀ HÀNG");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel1)
                                                                .addGap(91, 91, 91)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(22, Short.MAX_VALUE)
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(21, 21, 21)));

                btnQuayOrder.setBackground(new java.awt.Color(214, 85, 23));
                btnQuayOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnQuayOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Order.png"))); // NOI18N
                btnQuayOrder.setText("Quầy Order");
                btnQuayOrder.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnQuayOrderActionPerformed(evt);
                        }
                });

                btnLichSu.setBackground(new java.awt.Color(214, 85, 23));
                btnLichSu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnLichSu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Order-history.png"))); // NOI18N
                btnLichSu.setText("Lịch Sử Thanh Toán");
                btnLichSu.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLichSuActionPerformed(evt);
                        }
                });

                btnDsdv.setBackground(new java.awt.Color(214, 85, 23));
                btnDsdv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnDsdv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Menu.png"))); // NOI18N
                btnDsdv.setText("Danh Sách Dịch Vụ");
                btnDsdv.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDsdvActionPerformed(evt);
                        }
                });

                btnDatBan.setBackground(new java.awt.Color(214, 85, 23));
                btnDatBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnDatBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Booking.png"))); // NOI18N
                btnDatBan.setText("Đặt Bàn");
                btnDatBan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDatBanActionPerformed(evt);
                        }
                });

                btnThongKe.setBackground(new java.awt.Color(214, 85, 23));
                btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Statistics.png"))); // NOI18N
                btnThongKe.setText("Thống Kê Doanh Thu");
                btnThongKe.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnThongKeActionPerformed(evt);
                        }
                });

                btnDsnv.setBackground(new java.awt.Color(214, 85, 23));
                btnDsnv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnDsnv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/UserGroup.png"))); // NOI18N
                btnDsnv.setText("Danh Sách Nhân Viên");
                btnDsnv.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDsnvActionPerformed(evt);
                        }
                });

                btnLogOut.setBackground(new java.awt.Color(214, 85, 23));
                btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnLogOut.setText("Đăng xuất");
                btnLogOut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLogOutActionPerformed(evt);
                        }
                });

                btnInfo.setBackground(new java.awt.Color(197, 225, 172));
                btnInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Info.png"))); // NOI18N
                btnInfo.setBorder(null);
                btnInfo.setBorderPainted(false);
                btnInfo.setContentAreaFilled(false);
                btnInfo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnInfoActionPerformed(evt);
                        }
                });

                txtAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txtAccount.setText(" ");
                txtAccount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null,
                                new java.awt.Color(204, 255, 255), null, null));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(19, 19, 19)
                                                                .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(btnDatBan,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(btnQuayOrder,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(btnThongKe,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addGap(28, 28, 28)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(btnLichSu,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(btnDsdv,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(btnDsnv)))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(txtAccount,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                309,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(btnLogOut)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(btnInfo,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                65,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(21, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(21, 21, 21)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnLichSu)
                                                                                .addComponent(btnQuayOrder))
                                                                .addGap(24, 24, 24)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnDatBan)
                                                                                .addComponent(btnDsdv))
                                                                .addGap(24, 24, 24)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnThongKe)
                                                                                .addComponent(btnDsnv))
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(btnInfo)
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(30, 30, 30)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(txtAccount)
                                                                                                                .addComponent(btnLogOut))
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        public JLabel Acc() {
                return txtAccount;
        }

        public JButton btnDSNV() {
                return btnDsnv;
        }

        private void btnDsnvActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDsnvActionPerformed
                DanhSachNhanVien dsnv = new DanhSachNhanVien();
                dsnv.setLocationRelativeTo(null);
                dsnv.setVisible(true);
                // TODO add your handling code here:
        }// GEN-LAST:event_btnDsnvActionPerformed

        private void btnLichSuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLichSuActionPerformed
                LichSuThanhToan lstt = new LichSuThanhToan(account);
                lstt.setVisible(true);
                // TODO add your handling code here:
        }// GEN-LAST:event_btnLichSuActionPerformed

        private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {
                ThongKe thongKe = new ThongKe();
                thongKe.setVisible(true);
        }

        private void btnDsdvActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDsdvActionPerformed
                DanhSachDichVu dsnv = new DanhSachDichVu();
                dsnv.setVisible(true);
                // TODO add your handling code here:
        }// GEN-LAST:event_btnDsdvActionPerformed

        private void btnQuayOrderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnQuayOrderActionPerformed
                QuayOrder quayOrder = new QuayOrder(account);
                quayOrder.setVisible(true);
                quayOrder.nameNV().setText(account.getHo() + " " + account.getTen());
                // TODO add your handling code here:
        }// GEN-LAST:event_btnQuayOrderActionPerformed

        private void btnDatBanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDatBanActionPerformed
                DatBan datBan = new DatBan(account);
                datBan.setVisible(true);
                // TODO add your handling code here:
        }// GEN-LAST:event_btnDatBanActionPerformed

        private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLogOutActionPerformed
                LogIn login = new LogIn();
                login.setVisible(true);
                dispose();
                // TODO add your handling code here:
        }// GEN-LAST:event_btnLogOutActionPerformed

        private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInfoActionPerformed
                JOptionPane.showMessageDialog(rootPane,
                                "Đồ án quản lý nhà hàng \n Thực hiện bởi: \n Nguyễn Quốc Toản \n Nguyễn Ngọc Thông \n Nguyễn Đình Tiến \n Nếu có bất kì thắc mắc nào vui lòng liên hệ: 0999999999");
                // TODO add your handling code here:
        }// GEN-LAST:event_btnInfoActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnDatBan;
        private javax.swing.JButton btnDsdv;
        private javax.swing.JButton btnDsnv;
        private javax.swing.JButton btnInfo;
        private javax.swing.JButton btnLichSu;
        private javax.swing.JButton btnLogOut;
        private javax.swing.JButton btnQuayOrder;
        private javax.swing.JButton btnThongKe;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JLabel txtAccount;
        // End of variables declaration//GEN-END:variables
}
